apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iceland-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: www
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/sikalabs/charts.git
      path: ./charts/one-image
      helm:
        valuesObject:
          host: iceland-1.k3s.sikademo.com
          image: ondrejsika/iceland-1
          replicas: 2
